[package]
name = "nodi"
description = "A library for playback and abstraction of MIDI files."
version = "0.1.1"
edition = "2018"
license = "MIT"
authors = [ "Taylan Gökkaya <insomnimus.dev@gmail.com>" ]
categories = [ "multimedia::audio", "multimedia::encoding" ]
keywords = [ "midi", "audio", "music" ]
repository = "https://github.com/insomnimus/nodi"
readme = "readme.md"

[dependencies]
log = "0.4.14"
midir = "0.7.0"
midly = "0.5.2"
