[package]
name = "nodi"
description = "A library for playback and abstraction of MIDI files."
version = "0.12.0"
edition = "2018"
license = "MIT"
authors = [ "Taylan Gökkaya <insomnimus.dev@gmail.com>" ]
categories = [ "multimedia::audio", "multimedia::encoding" ]
keywords = [ "midi", "audio", "music" ]
repository = "https://github.com/insomnimus/nodi"
readme = "readme.md"

[package.metadata.docs.rs]
features = [ "midir", "verbose-log", "hybrid-sleep", "jack" ]
all-features = true

[[example]]
name = "play_midi"
required-features = [ "midir" ]

[dependencies]
log = "0.4.14"
midir = { version = "0.7.0", optional = true }
midly = "0.5.2"

[dev-dependencies]
clap = "3.0.0-beta.4"
midir = "0.7.0"

[features]
default = [ "hybrid-sleep" ]
verbose-log = []
hybrid-sleep = []
jack = ["midir/jack"]
winrt = ["midir/winrt"]
