[package]
name = "nodi"
version = "0.1.0"
edition = "2018"
license = "MIT"
authors = [ "Taylan Gökkaya <insomnimus.dev@gmail.com>" ]
categories = [ "multimedia::audio", "multimedia::encoding" ]
keywords = [ "midi", "audio", "music" ]

[dependencies]
log = "0.4.14"
midir = "0.7.0"
midly = "0.5.2"
