[package]
name = "nodi"
description = "A library for playback and abstraction of MIDI files."
version = "0.2.0"
edition = "2018"
license = "MIT"
authors = [ "Taylan Gökkaya <insomnimus.dev@gmail.com>" ]
categories = [ "multimedia::audio", "multimedia::encoding" ]
keywords = [ "midi", "audio", "music" ]
repository = "https://github.com/insomnimus/nodi"
readme = "readme.md"

[package.metadata.docs.rs]
features = [ "midir" ]
all-features = true

[dependencies]
log = "0.4.14"
midir = { version = "0.7.0", optional = true }
midly = "0.5.2"
