{
  "name": "Main",
  "on": [
    "push",
    "pull_request"
  ],
  "jobs": {
    "tests": {
      "name": "Tests",
      "strategy": {
        "matrix": {
          "os": [
            "macos-11",
            "windows-latest",
            "ubuntu-latest"
          ]
        }
      },
      "runs-on": "${{ matrix.os }}",
      "steps": [
        {
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Install Dependencies",
          "if": "matrix.os == 'ubuntu-latest'",
          "env": {
            "DEBIAN_FRONTEND": "noninteractive"
          },
          "run": "sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential pkg-config libasound2-dev"
        },
        {
          "name": "Stable",
          "run": "cargo test --all-features"
        },
        {
          "name": "Clippy",
          "if": "matrix.os == 'ubuntu-latest'",
          "run": "rustup component add clippy\ncargo clippy --all-targets --all-features\n"
        }
      ]
    },
    "publish": {
      "name": "Publish to crates.io",
      "if": "github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')",
      "needs": "tests",
      "runs-on": "windows-latest",
      "steps": [
        {
          "uses": "actions/checkout@v2.3.4"
        },
        {
          "name": "Publish",
          "run": "cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}"
        }
      ]
    }
  }
}
