{
  "name": "Main",
  "on": [
    "push",
    "pull_request"
  ],
  "jobs": {
    "tests": {
      "name": "Tests",
      "strategy": {
        "matrix": {
          "os": [
            "macos-11",
            "windows-latest",
            "ubuntu-latest"
          ]
        }
      },
      "runs-on": "${{ matrix.os }}",
      "steps": [
        {
          "name": "Setup | Checkout",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Setup | Rust",
          "uses": "actions-rs/toolchain@v1.0.7",
          "with": {
            "toolchain": "stable",
            "override": true,
            "profile": "minimal",
            "components": "clippy"
          }
        },
        {
          "name": "Test | Clippy",
          "uses": "actions-rs/cargo@v1.0.3",
          "with": {
            "command": "clippy",
            "args": "--features=midir"
          }
        },
        {
          "name": "Test | Test",
          "uses": "actions-rs/cargo@v1.0.3",
          "with": {
            "command": "test",
            "args": "--features=midir"
          }
        }
      ]
    },
    "publish": {
      "name": "Publish to crates.io",
      "if": "github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')",
      "needs": "tests",
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Setup | Checkout",
          "uses": "actions/checkout@v2.3.4"
        },
        {
          "name": "Setup | Rust",
          "uses": "actions-rs/toolchain@v1.0.7",
          "with": {
            "toolchain": "stable",
            "override": true,
            "profile": "minimal"
          }
        },
        {
          "name": "Deploy | Publish",
          "uses": "actions-rs/cargo@v1.0.3",
          "with": {
            "command": "publish",
            "args": "--token ${{ secrets.CRATES_IO_TOKEN }}"
          }
        }
      ]
    }
  }
}
